# Generated by Django 4.2.5 on 2023-10-07 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_customersupport_alter_address_customer'),
        ('Ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersupport',
            name='ticket_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ticket.customerticket'),
        ),
    ]
