# Generated by Django 4.2.5 on 2023-10-09 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0001_initial'),
        ('Account', '0004_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersupport',
            name='ticket_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ticket.customerticket'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('CS', 'Customer Support'), ('S', 'Supplier'), ('CU', 'Customer'), ('CO', 'Courier')], max_length=2),
        ),
    ]
