# Generated by Django 4.2.5 on 2023-10-10 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0002_alter_ticketcategory_options_and_more'),
        ('Account', '0007_user_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersupport',
            name='ticket_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ticket.customerticket'),
        ),
    ]
