# Generated by Django 4.2.5 on 2023-10-07 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0002_customersupport_alter_address_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTicket',
            fields=[
                ('ticket_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ticket_description', models.CharField(max_length=100)),
                ('ticket_date', models.DateField()),
                ('issue_status', models.CharField(choices=[('O', 'Open'), ('IP', 'In Progress'), ('C', 'Closed')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='TicketCategory',
            fields=[
                ('ticket_category_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=50)),
                ('ticket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ticket.customerticket')),
            ],
        ),
        migrations.AddField(
            model_name='customerticket',
            name='ticket_category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ticket.ticketcategory'),
        ),
        migrations.AddField(
            model_name='customerticket',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.customersupport'),
        ),
    ]
