# Generated by Django 4.2.5 on 2023-11-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0003_alter_customerticket_ticket_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerticket',
            name='issue_status',
            field=models.CharField(choices=[('O', 'Open'), ('C', 'Closed')], max_length=2),
        ),
    ]
