# Generated by Django 4.2.5 on 2023-09-29 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Review', '0001_initial'),
        ('Order', '0001_initial'),
        ('Payment', '0001_initial'),
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='review_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Review.review'),
        ),
        migrations.AddField(
            model_name='order',
            name='courier_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Account.courier'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Payment.payment'),
        ),
    ]
